// Curated PG-13 question pack for the iOS App Store version of Paranoia.
// No content about appearance, weight, sexuality, mental health, family, or anything that
// targets vulnerable groups. Focus on situational, hypothetical, and lighthearted prompts.

module.exports = [
  // ===== HYPOTHETICAL / WOULD SURVIVE =====
  "Who's most likely to survive a zombie apocalypse?",
  "Who's most likely to be the first to die in a horror movie?",
  "Who would survive the longest stranded on a deserted island?",
  "Who would you trust to lead the group out of a maze?",
  "Who's most likely to befriend a wild animal?",
  "Who would win in a game of hide and seek?",
  "Who's most likely to outrun a bear?",
  "Who would be the best hostage negotiator?",
  "Who's most likely to fall for a scam email?",
  "Who would be the worst person to cheat off in school?",
  "Who's most likely to become a billionaire?",
  "Who would survive the longest without their phone?",
  "Who's most likely to invent something useful?",
  "Who would be the best detective?",
  "Who's most likely to write a bestselling book?",
  "Who would be the worst at keeping a houseplant alive?",
  "Who's most likely to get lost in their own neighborhood?",
  "Who would be the best wedding planner?",
  "Who's most likely to win a game show?",
  "Who would be the best at building a treehouse?",
  "Who's most likely to become a famous chef?",
  "Who would survive the longest in the wilderness?",
  "Who's most likely to run a marathon on a dare?",
  "Who would be the best emergency babysitter?",
  "Who's most likely to start a successful YouTube channel?",
  "Who would be the worst at giving directions?",

  // ===== TALENT / SKILL =====
  "Who has the best singing voice?",
  "Who would be the best dance partner?",
  "Who has the best taste in music?",
  "Who's the most creative person here?",
  "Who has the best sense of humor?",
  "Who tells the best stories?",
  "Who's the best cook in the room?",
  "Who has the best handwriting?",
  "Who's the most photogenic?",
  "Who would win a karaoke contest?",
  "Who's the best at video games?",
  "Who has the best memory?",
  "Who's the fastest runner?",
  "Who's the best at math in their head?",
  "Who would win at trivia night?",
  "Who's the best at giving advice?",
  "Who has the best taste in movies?",
  "Who's the best driver?",
  "Who's the best at planning trips?",
  "Who would be the best teacher?",

  // ===== PERSONALITY VIBES =====
  "Who's the most adventurous?",
  "Who's the most loyal friend?",
  "Who's the most likely to remember everyone's birthday?",
  "Who's the funniest person here?",
  "Who's the most patient?",
  "Who's the most spontaneous?",
  "Who's the most organized?",
  "Who's the most easygoing?",
  "Who's the most curious?",
  "Who's the most ambitious?",
  "Who's the most generous?",
  "Who's the calmest in a crisis?",
  "Who's the best listener?",
  "Who's the most dramatic?",
  "Who's the most competitive?",
  "Who's the most laid back?",
  "Who's the biggest dreamer?",
  "Who's the most stubborn?",
  "Who's the most chill?",
  "Who's the biggest planner?",

  // ===== HABITS / QUIRKS =====
  "Who's most likely to be late to their own party?",
  "Who's most likely to forget where they parked?",
  "Who's most likely to talk to themselves out loud?",
  "Who's most likely to laugh at their own jokes?",
  "Who's most likely to fall asleep during a movie?",
  "Who has the messiest room?",
  "Who has the cleanest car?",
  "Who's most likely to leave dishes in the sink for a week?",
  "Who's most likely to text and walk into a pole?",
  "Who's most likely to take 100 photos of the same thing?",
  "Who's most likely to forget their password?",
  "Who's most likely to lose their keys daily?",
  "Who's most likely to overpack for a weekend trip?",
  "Who's most likely to start a project and never finish it?",
  "Who's most likely to binge-watch a whole show in one night?",
  "Who's most likely to keep a journal?",
  "Who's most likely to leave the group chat on read?",
  "Who's most likely to send a meme at 3 AM?",
  "Who's most likely to refuse to share their fries?",
  "Who's most likely to put pineapple on pizza?",

  // ===== TRAVEL / ADVENTURE =====
  "Who's most likely to move to another country?",
  "Who would be the best travel buddy?",
  "Who's most likely to skydive?",
  "Who's most likely to road trip across the country?",
  "Who would visit the most countries in their lifetime?",
  "Who's most likely to try every food in a new city?",
  "Who would be the worst at navigating a new place?",
  "Who's most likely to take a solo vacation?",
  "Who's most likely to camp in the woods alone?",
  "Who would be the best tour guide?",
  "Who's most likely to learn a new language for fun?",
  "Who would survive backpacking through Europe with no plan?",
  "Who's most likely to befriend strangers on a plane?",
  "Who would be the best at finding hidden gems on a trip?",
  "Who's most likely to lose their luggage?",

  // ===== POP CULTURE / FANDOMS =====
  "Who's most likely to be a Marvel superhero?",
  "Who would survive the Hunger Games?",
  "Who would win on Survivor?",
  "Who's most likely to go viral on TikTok?",
  "Who would be the best contestant on a cooking show?",
  "Who would be cast as the lead in a romantic comedy?",
  "Who's most likely to be in a documentary one day?",
  "Who would be the best Disney villain?",
  "Who would be the best superhero sidekick?",
  "Who's most likely to write fan fiction?",
  "Who would be the best Bachelor or Bachelorette contestant?",
  "Who would win The Amazing Race?",
  "Who's most likely to know every word to a musical?",
  "Who would be the best escape room teammate?",
  "Who's most likely to dress up for a movie premiere?",

  // ===== FUTURE PREDICTIONS =====
  "Who will be the first to own a house?",
  "Who will have the most kids?",
  "Who will retire the earliest?",
  "Who will become a CEO one day?",
  "Who will move the farthest from where they grew up?",
  "Who will start their own business?",
  "Who will write a book?",
  "Who will run for office one day?",
  "Who will become famous?",
  "Who will adopt the most pets?",
  "Who will travel to space if it became affordable?",
  "Who will be the best parent?",
  "Who will be the cool grandparent one day?",
  "Who will get the coolest job?",
  "Who will live in the biggest city?",

  // ===== SCENARIOS =====
  "Who would you call to help you move at 2 AM?",
  "Who would you trust with your phone unlocked?",
  "Who would you want as your lawyer?",
  "Who would be the best wingman or wingwoman?",
  "Who would you trust to plan your birthday?",
  "Who would you want to be stuck in an elevator with?",
  "Who would you call if you needed bail money for jaywalking?",
  "Who would be the best person to road trip with?",
  "Who would you trust to walk your dog?",
  "Who would be the best person to study with?",
  "Who would you trust to cut your hair?",
  "Who would you want as your roommate?",
  "Who would you trust to pick out an outfit for you?",
  "Who would be the best person to host a dinner party?",
  "Who would you want as your therapist?",
  "Who would you trust to give you a piggyback ride to safety?",
  "Who would you call first with good news?",
  "Who would be the best person to babysit your pet?",
  "Who would you trust with the aux cord on a road trip?",
  "Who would you want as a partner in a trivia contest?",

  // ===== FOOD =====
  "Who's the pickiest eater?",
  "Who would try the weirdest food on a dare?",
  "Who's most likely to become a vegetarian?",
  "Who would win a hot wing eating contest?",
  "Who's most likely to bake the best cookies?",
  "Who's most likely to burn water?",
  "Who eats the same thing every day?",
  "Who has the most adventurous palate?",
  "Who's most likely to have a coffee addiction?",
  "Who would survive the longest on just snacks?",

  // ===== SILLY / RANDOM =====
  "Who's most likely to talk to plants?",
  "Who's most likely to name their car?",
  "Who's most likely to believe in aliens?",
  "Who's most likely to start a band?",
  "Who's most likely to know a random fun fact for any topic?",
  "Who's most likely to win an award for nothing in particular?",
  "Who has the funniest laugh?",
  "Who would be the best at charades?",
  "Who's most likely to wear socks with sandals?",
  "Who would invent a new dance move that catches on?",
  "Who's most likely to high five a stranger?",
  "Who would name their kid something unusual?",
  "Who's most likely to cry happy tears at a wedding?",
  "Who would adopt a dozen rescue animals?",
  "Who's most likely to start every conversation with a compliment?",
  "Who's most likely to keep a lucky charm?",
  "Who's most likely to wear matching outfits with their best friend?",
  "Who would write the longest letter to a friend?",
  "Who's most likely to have a secret talent nobody knows about?",
  "Who would survive the longest without internet?",
];
