module.exports = [
  // ===== SPICY / WHO'S MOST LIKELY TO =====
  "Who here would be the worst person to share a secret with?",
  "Who's most likely to have a secret OnlyFans?",
  "Who here gives off the biggest freak energy?",
  "Who's most likely to hook up with someone in this room?",
  "Who here has definitely lied about their body count?",
  "Who's most likely to send a nude to the wrong person?",
  "Who here is the biggest flirt without realizing it?",
  "Who would be the worst one-night stand?",
  "Who here has the most questionable search history?",
  "Who's most likely to date someone twice their age?",
  "Who here is lowkey a stalker on social media?",
  "Who's most likely to get caught having sex in public?",
  "Who here has definitely faked an orgasm?",
  "Who would survive the longest on a dating show?",
  "Who here gives the best head? (based on vibes alone)",
  "Who's most likely to marry for money?",
  "Who here has the wildest Tinder stories?",
  "Who's most likely to cheat on a partner?",
  "Who here would be the best at phone sex?",
  "Who's most likely to sleep with a friend's ex?",
  "Who here has the biggest ego in bed?",
  "Who's most likely to have a secret sex tape?",
  "Who here would be the worst at dirty talk?",
  "Who's most likely to get caught watching porn at work?",
  "Who would you trust least with your partner?",
  "Who here is secretly the kinkiest?",
  "Who's most likely to have a friends-with-benefits situation go wrong?",
  "Who here has the worst taste in people they're attracted to?",
  "Who's most likely to fall in love with a stripper?",
  "Who here would be the most annoying person to live with?",
  "Who's most likely to get into a bar fight?",
  "Who here is the most likely to ghost someone after a great date?",
  "Who's most likely to accidentally send a sext to a family group chat?",
  "Who here is the biggest attention seeker?",
  "Who's most likely to have a breakdown at a party?",
  "Who here is secretly a terrible person?",
  "Who's most likely to steal someone's partner?",
  "Who here is the most manipulative?",
  "Who's most likely to cry during sex?",
  "Who here has the worst drunk texting habits?",
  "Who's most likely to make out with a stranger tonight?",
  "Who here smells the best?",
  "Who here smells the worst right now?",
  "Who's most likely to become a sugar baby?",
  "Who here has the most exes in this room?",
  "Who's most likely to date two people at once?",
  "Who here is the biggest lightweight?",
  "Who's most likely to throw up from drinking tonight?",
  "Who here has hooked up with someone in this room?",
  "Who would you want to be stranded on an island with?",
  "Who here is the most likely to have a threesome?",

  // ===== DARK / EDGY =====
  "Who here would you eliminate first in a zombie apocalypse?",
  "Who's most likely to end up in prison?",
  "Who here would sell everyone out for a million dollars?",
  "Who's most likely to fake their own death?",
  "Who here is secretly miserable?",
  "Who's most likely to become a cult leader?",
  "Who here is the biggest pathological liar?",
  "Who's most likely to end up on a true crime podcast?",
  "Who here would be the first to betray the group?",
  "Who's most likely to go completely off the grid?",
  "Who here is the most emotionally unavailable?",
  "Who's most likely to have a villain origin story?",
  "Who here has the darkest sense of humor?",
  "Who's most likely to survive a horror movie?",
  "Who here would die first in a horror movie?",
  "Who's most likely to become a conspiracy theorist?",
  "Who here is the most two-faced?",
  "Who's most likely to be running from something?",
  "Who here would make the best con artist?",
  "Who's most likely to disappear without telling anyone?",
  "Who here trusts no one in this room?",
  "Who's most likely to have committed a crime no one knows about?",
  "Who here gives off serial killer vibes?",
  "Who's most likely to be secretly wealthy?",
  "Who here is hiding the biggest secret?",

  // ===== EMBARRASSING =====
  "Who here has the worst fashion sense?",
  "Who's most likely to pee themselves laughing?",
  "Who here has the most embarrassing photo on their phone?",
  "Who's most likely to fall asleep during sex?",
  "Who here has the worst morning breath?",
  "Who's most likely to get pantsed in public?",
  "Who here is the loudest in bed?",
  "Who's most likely to walk into a glass door?",
  "Who here has the cringiest social media?",
  "Who's most likely to accidentally call a teacher 'mom'?",
  "Who here has the most embarrassing fetish?",
  "Who's most likely to fart during a first date?",
  "Who here talks the most shit behind people's backs?",
  "Who's most likely to get food stuck in their teeth and not notice?",
  "Who here has the worst dancing skills?",
  "Who's most likely to trip walking up stairs?",
  "Who here is the most socially awkward?",
  "Who's most likely to accidentally like an ex's photo from 3 years ago?",
  "Who here looks the most different without makeup?",
  "Who's most likely to show up to the wrong wedding?",

  // ===== RELATIONSHIP / ROMANCE =====
  "Who here would you want to go on a date with?",
  "Who's most likely to get married first?",
  "Who here would be the best partner?",
  "Who's most likely to be single forever?",
  "Who here gives the best hugs?",
  "Who's most likely to have an affair with a coworker?",
  "Who here is the most romantic?",
  "Who's most likely to write a love letter in 2026?",
  "Who here has the best relationship advice?",
  "Who's most likely to get divorced within a year of marriage?",
  "Who here is the most lovable?",
  "Who's most likely to fall for a catfish?",
  "Who here would you want as your valentine?",
  "Who's most likely to propose after one month of dating?",
  "Who here has had the worst breakup?",
  "Who's most likely to date someone their friends hate?",
  "Who here would you want to wake up next to?",
  "Who's most likely to get back with a toxic ex?",
  "Who here is the biggest hopeless romantic?",
  "Who's most likely to have a destination wedding no one can afford to attend?",

  // ===== PERSONALITY / VIBES =====
  "Who here has main character energy?",
  "Who's most likely to become famous?",
  "Who here is the funniest without trying?",
  "Who's most likely to win a reality TV show?",
  "Who here has the best smile?",
  "Who's most likely to become a politician?",
  "Who here has the most chaotic energy?",
  "Who's most likely to start a fight over nothing?",
  "Who here is the most trustworthy?",
  "Who's most likely to become a millionaire?",
  "Who here is the most underrated?",
  "Who's most likely to drop everything and travel the world?",
  "Who here has the best laugh?",
  "Who's most likely to go viral for something stupid?",
  "Who here is the most intimidating?",
  "Who's most likely to join a pyramid scheme?",
  "Who here gives the best advice?",
  "Who's most likely to become a Karen?",
  "Who here has the best style?",
  "Who's most likely to get a face tattoo?",
  "Who here is the most likely to cry at a movie?",
  "Who's most likely to peak in high school?",
  "Who here is the most competitive?",
  "Who's most likely to survive alone in the wilderness?",
  "Who here would be the worst boss?",

  // ===== PARTY / SOCIAL =====
  "Who here is the life of the party?",
  "Who's most likely to black out tonight?",
  "Who here always needs to be the center of attention?",
  "Who's most likely to start a fight at a bar?",
  "Who here is the most fun to drink with?",
  "Who's most likely to dance on a table?",
  "Who here always disappears at parties?",
  "Who's most likely to shotgun a beer right now?",
  "Who here is always the last to leave?",
  "Who's most likely to get kicked out of a club?",
  "Who here is the worst wingman/wingwoman?",
  "Who's most likely to make out with someone at every party?",
  "Who here always starts the drama?",
  "Who's most likely to get a noise complaint?",
  "Who here would throw the worst party?",
  "Who's most likely to skinny dip?",
  "Who here is the most likely to do a dare?",
  "Who's most likely to streak across a field?",
  "Who here always kills the vibe?",
  "Who's most likely to challenge someone to a drinking contest?",

  // ===== HYPOTHETICAL / WOULD YOU =====
  "Who would you pick to be your partner in a heist?",
  "Who here would you swap lives with for a day?",
  "Who would you pick to write your dating profile?",
  "Who here would you trust to plan your bachelor/bachelorette party?",
  "Who would you pick to defend you in court?",
  "Who here would you call at 3 AM?",
  "Who would you pick to be your fake boyfriend/girlfriend?",
  "Who here would you want to do a couples costume with?",
  "Who would you pick to give you a lap dance?",
  "Who here would you hire as a personal assistant?",
  "Who would you pick to be stuck in an elevator with?",
  "Who here would you trust with your phone for 24 hours?",
  "Who would you pick to star in a romantic comedy with?",
  "Who here would you choose to take body shots off of?",
  "Who would you pick to roast at a comedy show?",
  "Who here would you want to do karaoke with?",
  "Who would you pick to be your gym buddy?",
  "Who here would you share a bed with platonically?",
  "Who would you pick to take a road trip with?",
  "Who here would you want to give you a massage?",

  // ===== DEEP / THOUGHTFUL =====
  "Who here puts up the biggest front?",
  "Who's most likely to be dealing with something nobody knows about?",
  "Who here do you genuinely worry about?",
  "Who's most likely to change the most in 5 years?",
  "Who here needs a hug right now?",
  "Who's most likely to have a mid-life crisis at 30?",
  "Who here is the strongest mentally?",
  "Who's most likely to achieve their dreams?",
  "Who here has been through the most?",
  "Who's most likely to ghost everyone and start fresh?",
  "Who here needs to hear 'I'm proud of you'?",
  "Who's most likely to regret something they did this year?",
  "Who here is the bravest?",
  "Who's most likely to still be friends with everyone in 10 years?",
  "Who here deserves better than what they've gotten?",
  "Who's most likely to have an existential crisis this week?",
  "Who here is the wisest?",
  "Who's most likely to be hiding their pain behind humor?",
  "Who here would you want by your side in a crisis?",
  "Who's most likely to need therapy the most?",

  // ===== NSFW / VERY SPICY =====
  "Who here has the biggest dick energy?",
  "Who's most likely to own a sex toy collection?",
  "Who here would be the best kisser?",
  "Who's most likely to have had a one-night stand they regret?",
  "Who here gives off dominant energy?",
  "Who's most likely to be submissive in bed?",
  "Who here would look best in lingerie?",
  "Who's most likely to have an exhibitionist streak?",
  "Who here would you most want to see naked?",
  "Who's most likely to be into roleplay?",
  "Who here has the most sexual tension with another person in this room?",
  "Who's most likely to have sexted someone in this room?",
  "Who here looks like they'd be good in bed?",
  "Who's most likely to have a sex bucket list?",
  "Who here has the biggest flirting game?",
  "Who's most likely to have tried something wild in bed?",
  "Who here would you make a sex tape with?",
  "Who's most likely to have a praise kink?",
  "Who here would be the best at seduction?",
  "Who's most likely to have had sex in a car?",
  "Who here has the biggest 'I'd hit that' energy?",
  "Who's most likely to join a mile-high club?",
  "Who here is secretly a freak?",
  "Who's most likely to moan the loudest?",
  "Who here do you have a secret crush on?",
  "Who's most likely to be into BDSM?",
  "Who here would be the best at a strip tease?",
  "Who's most likely to skinny dip on a first date?",
  "Who here has the most hookup stories?",
  "Who's most likely to have a friends-with-benefits right now?",

  // ===== TRUST / LOYALTY =====
  "Who here would you trust with your life?",
  "Who's most likely to snitch?",
  "Who here always has your back?",
  "Who's most likely to spread a rumor?",
  "Who here is the most loyal friend?",
  "Who's most likely to backstab you?",
  "Who here would you tell your deepest secret to?",
  "Who's most likely to break a promise?",
  "Who here is the most reliable?",
  "Who's most likely to flake on plans?",
  "Who here is the most genuine?",
  "Who's most likely to lie to your face?",
  "Who here would bail you out of jail?",
  "Who's most likely to read your diary?",
  "Who here would cover for you no matter what?",
  "Who's most likely to expose your secrets if you had a falling out?",
  "Who here is the most honest?",
  "Who's most likely to throw you under the bus?",
  "Who here would donate a kidney for you?",
  "Who's most likely to screenshot your conversations?",

  // ===== WILD CARD / RANDOM =====
  "Who here would survive the longest in a zombie apocalypse?",
  "Who's most likely to accidentally start a fire?",
  "Who here would be the best superhero?",
  "Who's most likely to win a Nobel Prize?",
  "Who here would be the worst at keeping a poker face?",
  "Who's most likely to rob a bank?",
  "Who here has the most useless talent?",
  "Who's most likely to get arrested for something dumb?",
  "Who here would be the best at Among Us in real life?",
  "Who's most likely to adopt 10 cats?",
  "Who here would make the worst roommate?",
  "Who's most likely to eat something off the floor?",
  "Who here is secretly a genius?",
  "Who's most likely to call in sick for a hangover?",
  "Who here has the weirdest hobby?",
  "Who's most likely to win a hot dog eating contest?",
  "Who here would be the most entertaining on a podcast?",
  "Who's most likely to get lost in their own city?",
  "Who here has the most chaotic phone?",
  "Who's most likely to become a meme?",

  // ===== MORE SPICY ROUNDS =====
  "Who here would you want to play 7 minutes in heaven with?",
  "Who's most likely to have a walk of shame?",
  "Who here has the most game?",
  "Who's most likely to accidentally moan in public?",
  "Who here gives off top energy?",
  "Who's most likely to give off bottom energy?",
  "Who here would be the best at making someone jealous?",
  "Who's most likely to have a sugar daddy/mommy?",
  "Who here has hooked up with someone they shouldn't have?",
  "Who's most likely to have an affair?",
  "Who here would be the worst at hiding an affair?",
  "Who's most likely to catch feelings during a hookup?",
  "Who here is the biggest tease?",
  "Who's most likely to kiss someone in this room before the night ends?",
  "Who here secretly wants to hook up with someone in this room?",
  "Who's most likely to have a secret kink no one would guess?",
  "Who here would you swipe right on?",
  "Who's most likely to slide into a celebrity's DMs?",
  "Who here would you be jealous of dating someone you like?",
  "Who's most likely to be someone's sexual awakening?",

  // ===== CAREER / LIFE =====
  "Who here would be the worst CEO?",
  "Who's most likely to quit their job dramatically?",
  "Who here would be the best stripper name?",
  "Who's most likely to become an influencer?",
  "Who here would be the worst teacher?",
  "Who's most likely to write a tell-all book?",
  "Who here would be the best porn star name?",
  "Who's most likely to start a cult?",
  "Who here would survive the longest without their phone?",
  "Who's most likely to be on a reality dating show?",
  "Who here would be the worst at adulting?",
  "Who's most likely to blow all their money on something stupid?",
  "Who here would make the best trophy spouse?",
  "Who's most likely to have a secret double life?",
  "Who here would be the worst motivational speaker?",
  "Who's most likely to live in a van by choice?",
  "Who here would be the best at being famous?",
  "Who's most likely to peak right now?",
  "Who here would you hire first?",
  "Who's most likely to become a stay-at-home parent?",

  // ===== CHILDHOOD / PAST =====
  "Who here was definitely the weird kid in school?",
  "Who's most likely to still sleep with a stuffed animal?",
  "Who here peaked in high school?",
  "Who's most likely to lie about their age?",
  "Who here was the biggest troublemaker as a kid?",
  "Who's most likely to still be affected by their first heartbreak?",
  "Who here had an emo phase?",
  "Who's most likely to have been a bully?",
  "Who here was the teacher's pet?",
  "Who's most likely to have been caught doing something embarrassing by their parents?",
  "Who here had the most embarrassing MySpace/Facebook page?",
  "Who's most likely to still have their ex's nudes saved?",
  "Who here was the biggest nerd growing up?",
  "Who's most likely to lie about their first time?",
  "Who here had the worst haircut phase?",
  "Who's most likely to have practiced kissing on a pillow?",
  "Who here was the most popular in school?",
  "Who's most likely to have peed in a pool as an adult?",
  "Who here lost their virginity in the weirdest place?",
  "Who's most likely to have had an imaginary friend way too long?",

  // ===== SOCIAL MEDIA / MODERN =====
  "Who here has the thirstiest Instagram?",
  "Who's most likely to post a thirst trap right now?",
  "Who here checks their ex's social media the most?",
  "Who's most likely to have a finsta?",
  "Who here has the most toxic Twitter takes?",
  "Who's most likely to go viral for the wrong reasons?",
  "Who here is the most addicted to their phone?",
  "Who's most likely to catfish someone?",
  "Who here has the most unread messages?",
  "Who's most likely to be cancelled?",
  "Who here would have the worst podcast?",
  "Who's most likely to start a GoFundMe for something ridiculous?",
  "Who here has the most dating apps on their phone?",
  "Who's most likely to respond to a 'you up?' text at 2 AM?",
  "Who here is the biggest simp on social media?",
  "Who's most likely to post their entire relationship online?",
  "Who here has the most embarrassing TikTok history?",
  "Who's most likely to send an unsolicited pic?",
  "Who here refreshes their notifications the most?",
  "Who's most likely to stalk someone they just met?",

  // ===== FOOD / HABITS =====
  "Who here has the most disgusting eating habits?",
  "Who's most likely to eat an entire pizza alone?",
  "Who here is secretly a terrible cook?",
  "Who's most likely to drink milk straight from the carton?",
  "Who here has the weirdest food combination?",
  "Who's most likely to lick someone's plate?",
  "Who here is the pickiest eater?",
  "Who's most likely to eat something that fell in the toilet?",
  "Who here has the worst sleeping schedule?",
  "Who's most likely to not wash their hands after the bathroom?",
  "Who here takes the longest showers?",
  "Who's most likely to wear the same underwear two days in a row?",
  "Who here has the messiest room?",
  "Who's most likely to not change their sheets for a month?",
  "Who here bites their toenails?",

  // ===== MONEY / MATERIALISM =====
  "Who here is the cheapest?",
  "Who's most likely to never pay their share?",
  "Who here flexes the hardest with the least money?",
  "Who's most likely to go broke from shopping?",
  "Who here would sell out their friends for $10,000?",
  "Who's most likely to gamble away their savings?",
  "Who here is the most materialistic?",
  "Who's most likely to be in debt they're hiding?",
  "Who here would do anything for the right price?",
  "Who's most likely to marry purely for financial security?",

  // ===== FEARS / INSECURITIES =====
  "Who here is the most insecure?",
  "Who's most likely to pretend they're fine when they're not?",
  "Who here cares the most about what others think?",
  "Who's most likely to have a secret they'd die before revealing?",
  "Who here has the most irrational fear?",
  "Who's most likely to be afraid of the dark?",
  "Who here would scream the loudest at a haunted house?",
  "Who's most likely to cry if someone yelled at them?",
  "Who here is the most afraid of commitment?",
  "Who's most likely to need constant reassurance?",

  // ===== DRUNK / PARTY BEHAVIOR =====
  "Who here is the most annoying when drunk?",
  "Who's most likely to drunk call their ex?",
  "Who here gets the most emotional when drinking?",
  "Who's most likely to start crying at a party?",
  "Who here gets the most aggressive when drunk?",
  "Who's most likely to lose their phone every time they go out?",
  "Who here is the most reckless when drinking?",
  "Who's most likely to wake up in a random place?",
  "Who here has the worst hangover behavior?",
  "Who's most likely to challenge someone to a fight when drunk?",
  "Who here is the horniest drunk?",
  "Who's most likely to make a drunk purchase they regret?",
  "Who here turns into a completely different person when drunk?",
  "Who's most likely to drunk text everyone in their contacts?",
  "Who here can't handle their alcohol at all?",

  // ===== ROUND 2 - MORE QUESTIONS =====
  "Who here would be the best at a staring contest?",
  "Who's most likely to accidentally reveal a surprise party?",
  "Who here has the most annoying laugh?",
  "Who's most likely to cry at their own wedding?",
  "Who here would be the worst at keeping a straight face during a lie?",
  "Who's most likely to forget someone's name mid-conversation?",
  "Who here has the best poker face?",
  "Who's most likely to accidentally walk into the wrong bathroom?",
  "Who here is the most gullible?",
  "Who's most likely to believe a ridiculous conspiracy theory?",
  "Who here would be the worst spy?",
  "Who's most likely to fall asleep in a weird place?",
  "Who here has the most random knowledge?",
  "Who's most likely to be caught talking to themselves?",
  "Who here gives the worst gifts?",
  "Who's most likely to regift something?",
  "Who here has the most road rage?",
  "Who's most likely to cry over a commercial?",
  "Who here is the worst driver?",
  "Who's most likely to leave their car unlocked all day?",

  // ===== HYPOTHETICAL SCENARIOS =====
  "Who would you pick to be your partner on The Amazing Race?",
  "Who here would you want writing your eulogy?",
  "Who would you trust to raise your kids?",
  "Who here would be the worst babysitter?",
  "Who would you want as your lawyer if you committed a crime?",
  "Who here would you pick for your apocalypse survival team?",
  "Who would you want to switch bodies with?",
  "Who here would you want as your wingman for one night?",
  "Who would you pick to give the toast at your wedding?",
  "Who here would be the most entertaining cellmate?",
  "Who would you pick to be stranded at sea with?",
  "Who here would you want to teach you how to fight?",
  "Who would you pick to go skydiving with?",
  "Who here would be the worst person to share a bathroom with?",
  "Who would you pick to be your designated driver for life?",

  // ===== ATTRACTION / PHYSICAL =====
  "Who here has the best body?",
  "Who's most likely to look good in anything?",
  "Who here has the most attractive voice?",
  "Who's most likely to get better looking with age?",
  "Who here has the best eyes?",
  "Who's most likely to be a model?",
  "Who here is the most photogenic?",
  "Who's most likely to be told they look like a celebrity?",
  "Who here has the best hair?",
  "Who's most likely to be the hottest person at any party?",
  "Who here ages like fine wine?",
  "Who's most likely to get the most attention at a beach?",
  "Who here has the best jawline?",
  "Who's most likely to look good first thing in the morning?",
  "Who here dresses the sexiest?",

  // ===== FRIENDSHIP =====
  "Who here would you call first in an emergency?",
  "Who's most likely to forget your birthday?",
  "Who here knows the most about you?",
  "Who's most likely to move away and never visit?",
  "Who here would you go into business with?",
  "Who's most likely to flake on important events?",
  "Who here has the most inside jokes with you?",
  "Who's most likely to accidentally insult you?",
  "Who here would you want to live next door to?",
  "Who's most likely to borrow money and not pay it back?",
  "Who here is your ride or die?",
  "Who's most likely to make new friends and forget the old ones?",
  "Who here would you trust with your pet?",
  "Who's most likely to spoil a movie?",
  "Who here is the friend everyone deserves?",

  // ===== GUILTY PLEASURES =====
  "Who here has the guiltiest pleasure they'd never admit?",
  "Who's most likely to binge-watch a kids' show?",
  "Who here secretly loves reality TV?",
  "Who's most likely to still listen to their middle school playlist?",
  "Who here reads fanfiction?",
  "Who's most likely to know all the words to a Nickelback song?",
  "Who here has a secret obsession nobody knows about?",
  "Who's most likely to cry at a Nicholas Sparks movie?",
  "Who here has a guilty pleasure app on their phone?",
  "Who's most likely to watch ASMR to fall asleep?",

  // ===== MORE EDGY =====
  "Who here has the most toxic trait?",
  "Who's most likely to gaslight someone?",
  "Who here is the biggest narcissist?",
  "Who's most likely to breadcrumb someone?",
  "Who here has the worst attachment style?",
  "Who's most likely to love-bomb someone?",
  "Who here is the most passive-aggressive?",
  "Who's most likely to give someone the silent treatment for days?",
  "Who here holds grudges the longest?",
  "Who's most likely to bring up old arguments?",
  "Who here is the most jealous?",
  "Who's most likely to go through someone's phone?",
  "Who here is the most controlling?",
  "Who's most likely to keep score in a relationship?",
  "Who here has the worst temper?",
  "Who's most likely to key someone's car?",
  "Who here is the pettiest?",
  "Who's most likely to subtweet someone?",
  "Who here talks the most trash?",
  "Who's most likely to make a scene in public?",

  // ===== WOULD THEY EVER =====
  "Who here would do a nude photoshoot for art?",
  "Who's most likely to try every drug at least once?",
  "Who here would eat a bug for $100?",
  "Who's most likely to get a tattoo on a dare?",
  "Who here would go on a blind date set up by their mom?",
  "Who's most likely to try an open relationship?",
  "Who here would shave their head for $500?",
  "Who's most likely to sext a stranger?",
  "Who here would participate in a kissing booth?",
  "Who's most likely to make a bet they can't win?",
  "Who here would wear a revealing outfit to church?",
  "Who's most likely to skinny dip in the ocean?",
  "Who here would kiss everyone in this room for $1000?",
  "Who's most likely to try pole dancing?",
  "Who here would let someone else pick their partner?",
  "Who's most likely to try tantric yoga?",
  "Who here would do a body shot off a stranger?",
  "Who's most likely to enter a beauty pageant?",
  "Who here would go commando for a week?",
  "Who's most likely to post a nude on main?",

  // ===== SECRETS & LIES =====
  "Who here is lying about something right now?",
  "Who's most likely to have a fake ID?",
  "Who here has catfished someone before?",
  "Who's most likely to have a secret social media account?",
  "Who here has lied about where they were?",
  "Who's most likely to have a secret relationship?",
  "Who here has pretended to be someone they're not?",
  "Who's most likely to have a burner phone?",
  "Who here has a secret they haven't told their best friend?",
  "Who's most likely to be leading a double life?",
  "Who here lies about liking someone's cooking?",
  "Who's most likely to have a secret admirer they know about?",
  "Who here has faked being sick to avoid plans?",
  "Who's most likely to pretend they don't see someone in public?",
  "Who here has texted someone while sitting next to them?",
  "Who's most likely to eavesdrop on strangers?",
  "Who here reads other people's texts over their shoulder?",
  "Who's most likely to tell a secret they swore to keep?",
  "Who here has snooped through someone's things?",
  "Who's most likely to have a hidden folder on their phone?",

  // ===== CHAOS & MISCHIEF =====
  "Who here would hack into their ex's account?",
  "Who's most likely to toilet paper someone's house?",
  "Who here would steal a stop sign?",
  "Who's most likely to prank call their boss?",
  "Who here would crash a wedding?",
  "Who's most likely to start a food fight?",
  "Who here would ding dong ditch at 30?",
  "Who's most likely to pull a fire alarm for fun?",
  "Who here would sneak into a movie theater?",
  "Who's most likely to key their ex's car?",
  "Who here would egg someone's house?",
  "Who's most likely to swap someone's drink?",
  "Who here would steal from a hotel room?",
  "Who's most likely to cause a scene at a restaurant?",
  "Who here would lie on a resume?",

  // ===== DATING & HOOKUP CULTURE =====
  "Who here swipes right on everyone?",
  "Who's most likely to lie about their height on a dating app?",
  "Who here uses the worst pickup lines?",
  "Who's most likely to go home with someone tonight?",
  "Who here has the most Tinder matches?",
  "Who's most likely to have been on more than 3 dating apps?",
  "Who here sends the first message?",
  "Who's most likely to ghost after the first date?",
  "Who here overthinks texts the most?",
  "Who's most likely to send a risky text they regret?",
  "Who here has the longest talking stage?",
  "Who's most likely to catch feelings from a hookup?",
  "Who here is the biggest player?",
  "Who's most likely to have a roster?",
  "Who here gives mixed signals?",
  "Who's most likely to text back immediately every time?",
  "Who here plays the most mind games?",
  "Who's most likely to stalk someone's LinkedIn before a date?",
  "Who here has been on the worst date ever?",
  "Who's most likely to date someone for free meals?",

  // ===== WORK / PROFESSIONAL =====
  "Who here has hooked up with a coworker?",
  "Who's most likely to have a work crush right now?",
  "Who here would flirt to get a promotion?",
  "Who's most likely to get fired for their behavior at a work party?",
  "Who here procrastinates the most at work?",
  "Who's most likely to have an inappropriate relationship with their boss?",
  "Who here has trash-talked their boss the most?",
  "Who's most likely to cry in the office bathroom?",
  "Who here steals the most office supplies?",
  "Who's most likely to quit via text?",

  // ===== INTERNET / POP CULTURE =====
  "Who here would thirst-follow a celebrity?",
  "Who's most likely to create a stan account?",
  "Who here knows the most celebrity gossip?",
  "Who's most likely to buy a celebrity's bath water?",
  "Who here would be the best reality TV villain?",
  "Who's most likely to write fan mail?",
  "Who here has the most parasocial relationships?",
  "Who's most likely to get obsessed with a fictional character?",
  "Who here would pay for a celebrity meet and greet?",
  "Who's most likely to name their kid after a celebrity?",

  // ===== SUPERLATIVES =====
  "Who here has the biggest heart?",
  "Who's most likely to be a secret softie?",
  "Who here pretends to be tough but is actually sensitive?",
  "Who's most likely to cry at a dog video?",
  "Who here is the most emotionally intelligent?",
  "Who's most likely to give great relationship advice but not follow it?",
  "Who here has the most sass?",
  "Who's most likely to clap back perfectly?",
  "Who here is the most extra?",
  "Who's most likely to overdress for everything?",
  "Who here has the most charisma?",
  "Who's most likely to talk their way out of a ticket?",
  "Who here is the most book-smart?",
  "Who's most likely to have the most street smarts?",
  "Who here is the most creative?",

  // ===== WHAT WOULD THEY DO =====
  "Who here would marry someone they just met in Vegas?",
  "Who's most likely to adopt a random stray animal?",
  "Who here would move to another country on a whim?",
  "Who's most likely to get a random piercing?",
  "Who here would impulsively dye their hair a crazy color?",
  "Who's most likely to quit their job without a backup plan?",
  "Who here would text their crush right now if dared?",
  "Who's most likely to jump off a cliff into water?",
  "Who here would get a matching tattoo with a stranger?",
  "Who's most likely to say yes to anything?",
  "Who here would eat the world's hottest pepper?",
  "Who's most likely to enter a dance battle?",
  "Who here would sing karaoke sober?",
  "Who's most likely to flash someone on a dare?",
  "Who here would lick the floor for $50?",

  // ===== JUDGMENT CALLS =====
  "Who here has the worst judgment?",
  "Who's most likely to text something they shouldn't?",
  "Who here makes the worst decisions at 2 AM?",
  "Who's most likely to trust the wrong person?",
  "Who here has the worst taste in music?",
  "Who's most likely to date someone their parents would hate?",
  "Who here has the worst priorities?",
  "Who's most likely to pick a fight with the wrong person?",
  "Who here gives the worst first impressions?",
  "Who's most likely to show up late to everything?",
  "Who here has the worst poker face?",
  "Who's most likely to blurt out something inappropriate?",
  "Who here overthinks everything?",
  "Who's most likely to double-text?",
  "Who here is the worst at reading the room?",

  // ===== ROUND 3 - EVEN MORE =====
  "Who here looks like they'd be into feet?",
  "Who's most likely to have tried some questionable substances?",
  "Who here radiates big spoon energy?",
  "Who's most likely to be little spoon?",
  "Who here would you trust to cut your hair?",
  "Who's most likely to pull off a bald look?",
  "Who here has the most infectious energy?",
  "Who's most likely to light up any room they walk into?",
  "Who here is the most underestimated?",
  "Who's most likely to surprise everyone?",
  "Who here is secretly the smartest?",
  "Who's most likely to already be plotting something?",
  "Who here has the best comebacks?",
  "Who's most likely to roast you and make you laugh?",
  "Who here has the most big brother/sister energy?",
  "Who's most likely to protect everyone in this room?",
  "Who here gives the warmest energy?",
  "Who's most likely to make everyone feel welcome?",
  "Who here is lowkey the most powerful person in the room?",
  "Who's most likely to take over the world?",

  // ===== RELATIONSHIP RED FLAGS =====
  "Who here would be the worst to date?",
  "Who's most likely to text their ex 'I miss you' tonight?",
  "Who here has the biggest red flag?",
  "Who's most likely to ignore red flags?",
  "Who here would stay in a toxic relationship the longest?",
  "Who's most likely to be the toxic one in a relationship?",
  "Who here would break up over text?",
  "Who's most likely to get jealous over a like?",
  "Who here checks their partner's phone?",
  "Who's most likely to make their partner jealous on purpose?",
  "Who here has the most ex drama?",
  "Who's most likely to take back a cheater?",
  "Who here moves too fast in relationships?",
  "Who's most likely to propose way too early?",
  "Who here catches feelings too fast?",
  "Who's most likely to say 'I love you' first on a first date?",
  "Who here is the most emotionally unavailable person you know?",
  "Who's most likely to lead someone on?",
  "Who here doesn't know what they want?",
  "Who's most likely to be in a situationship right now?",

  // ===== BODY LANGUAGE & ENERGY =====
  "Who here gives off the most sexual energy without trying?",
  "Who's most likely to make someone uncomfortable with eye contact?",
  "Who here has the most intense stare?",
  "Who's most likely to undress someone with their eyes?",
  "Who here fidgets the most?",
  "Who's most likely to talk with their hands?",
  "Who here has the most relaxed energy?",
  "Who's most likely to fall asleep anywhere?",
  "Who here gives off the most mysterious vibes?",
  "Who's most likely to have a secret nobody would ever guess?",

  // ===== FANTASY / IMAGINATION =====
  "Who here would be the best vampire?",
  "Who's most likely to be a witch/warlock?",
  "Who here would survive the Hunger Games?",
  "Who's most likely to be sorted into Slytherin?",
  "Who here would make the best villain in a movie?",
  "Who's most likely to be the final girl in a horror film?",
  "Who here would be the best at seducing a spy?",
  "Who's most likely to be a secret agent?",
  "Who here would win The Bachelor/Bachelorette?",
  "Who's most likely to be chosen first for a heist crew?",

  // ===== BRUTAL HONESTY =====
  "Who here do you secretly find annoying sometimes?",
  "Who's most likely to think they're funnier than they are?",
  "Who here needs to hear the truth but nobody tells them?",
  "Who's most likely to have an ego problem?",
  "Who here is in denial about something?",
  "Who's most likely to be the one everyone talks about when they leave?",
  "Who here doesn't realize how they come across?",
  "Who's most likely to be completely different from how they present themselves?",
  "Who here tries too hard to be cool?",
  "Who's most likely to overestimate their looks?",

  // ===== SCENARIOS =====
  "If this room was a group chat, who would be muted?",
  "If everyone in this room was on a deserted island, who would be the leader?",
  "If this group was in a sitcom, who would be the comic relief?",
  "If everyone in this room applied for the same job, who would get it?",
  "If this group was a band, who would be the frontman?",
  "If everyone here was in a love triangle, who would be in the middle?",
  "If this room was a reality show house, who would get eliminated first?",
  "If everyone here was in prison, who would be the ringleader?",
  "If this group was on a ship, who would be thrown overboard first?",
  "If everyone in this room was a drink, who would be the strongest shot?",
  "If this group had to sacrifice one person to save the rest, who goes?",
  "If everyone here was a character in a drama, who would have the most plot twists?",
  "If this group was a heist crew, who would be the one to crack under pressure?",
  "If everyone here had a superpower, who would use it for evil?",
  "If this room was a dating pool, who would have the most options?",

  // ===== CONFESSION STYLE =====
  "Who here has definitely done something illegal this month?",
  "Who's most likely to have a confession that would shock everyone?",
  "Who here is hiding a crush on someone in this room?",
  "Who's most likely to have a secret they'd take to the grave?",
  "Who here has lied about their relationship status?",
  "Who's most likely to be pretending to be happy right now?",
  "Who here has a guilty conscience about something recent?",
  "Who's most likely to be thinking about someone else right now?",
  "Who here has done something they'd be mortified if it came out?",
  "Who's most likely to confess something shocking tonight?",

  // ===== LIFESTYLE =====
  "Who here spends the most money on their appearance?",
  "Who's most likely to get plastic surgery?",
  "Who here is the most high maintenance?",
  "Who's most likely to spend $500 on a single night out?",
  "Who here has the most expensive taste?",
  "Who's most likely to become a fitness influencer?",
  "Who here takes the most selfies?",
  "Who's most likely to have a skincare routine that costs more than rent?",
  "Who here is the biggest gym rat?",
  "Who's most likely to do a juice cleanse?",

  // ===== FINAL STRETCH - WILD ONES =====
  "Who here has the energy of someone who bites during sex?",
  "Who's most likely to be into choking?",
  "Who here looks like they'd be a screamer?",
  "Who's most likely to have a daddy/mommy kink?",
  "Who here gives off the vibes of someone who likes it rough?",
  "Who's most likely to have tried something they'll never admit to?",
  "Who here has the most innocent face but dirtiest mind?",
  "Who's most likely to have a body count way higher than people think?",
  "Who here gives off energy that says 'I've seen things'?",
  "Who's most likely to have hooked up in a bathroom stall?",
  "Who here would be the most fun in a hot tub?",
  "Who's most likely to have received or sent a spicy voice note?",
  "Who here has 'trouble' written all over them?",
  "Who's most likely to ruin a friendship by catching feelings?",
  "Who here is someone's type but won't admit it?",
  "Who's most likely to have a wild phase they never talk about?",
  "Who here looks like they'd leave you on read just to be petty?",
  "Who's most likely to break someone's heart and not feel bad?",
  "Who here has chemistry with someone in this room right now?",
  "Who's most likely to be the reason for someone's therapy?",

  // ===== BONUS ROUNDS =====
  "Who here would be the worst at a lie detector test?",
  "Who's most likely to get hypnotized?",
  "Who here would fail a polygraph about their love life?",
  "Who's most likely to accidentally expose themselves?",
  "Who here would look the best in a mugshot?",
  "Who's most likely to get arrested on vacation?",
  "Who here has main character syndrome?",
  "Who's most likely to make everything about themselves?",
  "Who here needs the most attention from the opposite sex?",
  "Who's most likely to have the most embarrassing browser history?",
  "Who here would eat the most in an eating competition?",
  "Who's most likely to do something crazy for attention?",
  "Who here would survive the longest without human contact?",
  "Who's most likely to crack first in solitary confinement?",
  "Who here is most afraid of being alone?",
  "Who's most likely to settle just so they're not single?",
  "Who here is the most independent?",
  "Who's most likely to need nobody but themselves?",
  "Who here is the most loyal to a fault?",
  "Who's most likely to forgive the unforgivable?",

  // ===== ULTRA SPICY BONUS =====
  "Who here has the most sexual energy in this room?",
  "Who's most likely to have a one-night stand and never think about it again?",
  "Who here could seduce anyone in this room?",
  "Who's most likely to have slept with someone famous?",
  "Who here looks like they'd be worth the drama?",
  "Who's most likely to send nudes they shouldn't?",
  "Who here would you follow into a bedroom no questions asked?",
  "Who's most likely to have done something scandalous at a wedding?",
  "Who here makes you question your sexuality?",
  "Who's most likely to be into someone here but too proud to admit it?",
  "Who here would be the best at truth or dare?",
  "Who's most likely to always pick dare?",
  "Who here would you want to play spin the bottle with?",
  "Who's most likely to have the wildest bucket list?",
  "Who here would you kiss on a dare?",
  "Who's most likely to have a hidden tattoo in an intimate place?",
  "Who here has the most confident walk?",
  "Who's most likely to own the room when they enter?",
  "Who here would you Netflix and actually chill with?",
  "Who's most likely to fall asleep during Netflix and chill?",

  // ===== PACK 2 - FRESH QUESTIONS =====
  "Who here secretly thinks they're better than everyone?",
  "Who's most likely to be a terrible influence?",
  "Who here would you not want your sibling to date?",
  "Who's most likely to ruin a group vacation?",
  "Who here is the most dramatic about minor things?",
  "Who's most likely to create problems that don't exist?",
  "Who here has the most chaotic love life?",
  "Who's most likely to end up on a tabloid?",
  "Who here gives unreliable narrator vibes?",
  "Who's most likely to exaggerate every story?",
  "Who here has the biggest sweet tooth?",
  "Who's most likely to eat in bed?",
  "Who here snores the loudest?",
  "Who's most likely to hog the blanket?",
  "Who here would be the worst travel companion?",
  "Who's most likely to forget their passport?",
  "Who here would panic the most in an emergency?",
  "Who's most likely to freeze during a crisis?",
  "Who here has the worst sense of direction?",
  "Who's most likely to get lost in a parking lot?",
  "Who here would be the first to break under interrogation?",
  "Who's most likely to confess to a crime they didn't commit?",
  "Who here is the most accident-prone?",
  "Who's most likely to break something valuable?",
  "Who here has the worst luck?",
  "Who's most likely to win the lottery and lose the ticket?",
  "Who here is the most superstitious?",
  "Who's most likely to blame Mercury retrograde for everything?",
  "Who here has the most toxic positivity?",
  "Who's most likely to say 'everything happens for a reason' at the worst time?",

  // ===== SPECIFIC SCENARIOS =====
  "Who would you pick to be your partner on a survival show?",
  "Who here would eat the last slice of pizza without asking?",
  "Who would you want sitting next to you on a 12-hour flight?",
  "Who here would you NOT want sitting next to you on a 12-hour flight?",
  "Who would you pick to plan your surprise birthday party?",
  "Who here would give the most chaotic best man/maid of honor speech?",
  "Who would you pick to go shopping with?",
  "Who here would max out your credit card?",
  "Who would you trust to hold your drink at a party?",
  "Who here would definitely drink your drink?",
  "Who would you pick to go to a haunted house with?",
  "Who here would push you toward the ghost?",
  "Who would you pick to do a tandem skydive with?",
  "Who here would scream the entire time?",
  "Who would you trust to take care of your plants?",

  // ===== RAPID FIRE SPICY =====
  "Who here has definitely sexted today?",
  "Who's most likely to have a hickey hidden right now?",
  "Who here looks like they haven't slept because they were up all night... not sleeping?",
  "Who's most likely to moan while eating good food?",
  "Who here gives off 'I need to get laid' energy?",
  "Who's most likely to slide into someone's DMs after this game?",
  "Who here is undressing someone with their eyes right now?",
  "Who's most likely to dream about someone in this room tonight?",
  "Who here would make the best arm candy?",
  "Who's most likely to be someone's hall pass?",
  "Who here has the most magnetic personality?",
  "Who's most likely to get away with anything because of their charm?",
  "Who here could talk anyone into anything?",
  "Who's most likely to be dangerously persuasive?",
  "Who here would be the best cult leader?",

  // ===== FRIEND GROUP DYNAMICS =====
  "Who is the mom/dad of this group?",
  "Who here is the baby of the group?",
  "Who's the one person in this group everyone has a different relationship with?",
  "Who here has the most influence over the group?",
  "Who's the first person to start a group chat argument?",
  "Who here is always playing devil's advocate?",
  "Who's the peacemaker of this group?",
  "Who here secretly thinks they should be in charge?",
  "Who's the funniest person in this room?",
  "Who here tries too hard to be funny?",
  "Who's the most likely to organize plans?",
  "Who here never initiates plans but always shows up?",
  "Who's the first to leave every hangout?",
  "Who here would be the last to know group gossip?",
  "Who here is the glue holding this group together?",

  // ===== DEEP DARK =====
  "Who here has thought about cutting someone off and hasn't yet?",
  "Who's most likely to have cried themselves to sleep this week?",
  "Who here is carrying the heaviest burden right now?",
  "Who's most likely to never ask for help even when they need it?",
  "Who here would you save first in a burning building?",
  "Who's most likely to sacrifice themselves for someone else?",
  "Who here has the most regrets?",
  "Who's most likely to be haunted by their past?",
  "Who here puts others before themselves too much?",
  "Who's most likely to lose themselves in a relationship?",
  "Who here is the most self-destructive?",
  "Who's most likely to push people away when they get too close?",
  "Who here has walls up that nobody can break through?",
  "Who's most likely to pretend they don't care when they care the most?",
  "Who here deserves way more credit than they get?",

  // ===== PARTY GAMES CROSSOVER =====
  "Who here would be the worst at never have I ever?",
  "Who's most likely to have done everything in 'never have I ever'?",
  "Who here would be eliminated first in truth or dare?",
  "Who's most likely to refuse a dare?",
  "Who here would dominate at beer pong?",
  "Who's most likely to challenge everyone to arm wrestling?",
  "Who here would win a twerking contest?",
  "Who's most likely to do the worm on the dance floor?",
  "Who here would win a sexiest dance competition?",
  "Who's most likely to start a conga line?",

  // ===== MODERN DATING =====
  "Who here has the most toxic texting habits?",
  "Who's most likely to leave someone on delivered for days?",
  "Who here has been in a situationship for way too long?",
  "Who's most likely to catch feelings from a dating app?",
  "Who here gives the best first date energy?",
  "Who's most likely to overshare on a first date?",
  "Who here has the most game on dating apps?",
  "Who's most likely to have their friend run their dating profile?",
  "Who here takes the best selfies for dating apps?",
  "Who's most likely to use a photo from 5 years ago?",
  "Who here has the best flirting technique?",
  "Who's most likely to be completely oblivious when someone flirts with them?",
  "Who here would be the most awkward on a first date?",
  "Who's most likely to talk about their ex on a date?",
  "Who here would go on a date with anyone just for the story?",

  // ===== ULTIMATE QUESTIONS =====
  "If you could only save one person in this room, who would it be?",
  "Who here would you want to be the last person you ever talk to?",
  "Who in this room has changed your life the most?",
  "Who here would you erase from your memory if you could?",
  "Who's the person you'd miss the most if they left right now?",
  "Who here do you admire the most?",
  "Who's the person you'd want to grow old with?",
  "Who here makes you feel the safest?",
  "Who's the person you'd want to share your last meal with?",
  "Who here do you think about more than they know?",
  "Who in this room is your biggest inspiration?",
  "Who here has surprised you the most since you've known them?",
  "Who's the person you'd trust with your deepest, darkest secret?",
  "Who here knows the real you?",
  "Who's the person that understands you the best in this room?",
  "Who here has the power to hurt you the most?",
  "Who's the person you've learned the most from?",
  "Who here would you go to war for?",
  "Who's the person you'd take a bullet for without thinking?",
  "Who here do you wish you were closer with?",

  // ===== EXTRA PACK - REACHING 1000+ =====
  "Who here would be the hottest as the opposite gender?",
  "Who's most likely to accidentally set something on fire?",
  "Who here would survive longest in a haunted house?",
  "Who's most likely to believe in ghosts after tonight?",
  "Who here has the most punchable face (with love)?",
  "Who's most likely to get into an argument with a stranger?",
  "Who here would look the best bald?",
  "Who's most likely to shave their eyebrows on a dare?",
  "Who here would be the funniest stand-up comedian?",
  "Who's most likely to bomb on stage?",
  "Who here has the most contagious laugh?",
  "Who's most likely to laugh at the worst possible time?",
  "Who here would be the worst at flirting?",
  "Who's most likely to accidentally offend someone?",
  "Who here takes the longest to get ready?",
  "Who's most likely to cancel plans last minute?",
  "Who here would be the best stripper?",
  "Who's most likely to be into older people?",
  "Who here gives off cougar/silver fox energy?",
  "Who's most likely to date someone way younger?",
  "Who here has the spiciest camera roll?",
  "Who's most likely to accidentally show someone an embarrassing photo?",
  "Who here has the most screen time on their phone?",
  "Who's most likely to not survive without WiFi for a day?",
  "Who here gives off the best cuddling vibes?",
  "Who's most likely to be a blanket hogger?",
  "Who here would be the worst person to share a tent with?",
  "Who's most likely to snore and deny it?",
  "Who here has the best neck?",
  "Who's most likely to have the most hickeys at once?",
  "Who here would win in a pillow fight?",
  "Who's most likely to take a pillow fight too seriously?",
  "Who here has the most expressive face?",
  "Who's most likely to be an open book?",
  "Who here is the hardest to read?",
  "Who's most likely to be hiding what they really feel right now?",
  "Who here would eat the weirdest thing on a dare?",
  "Who's most likely to eat something they're allergic to just to be polite?",
  "Who here has the strongest immune system?",
  "Who's most likely to call in sick when they're perfectly fine?",
  "Who here would be the best at giving a TED talk?",
  "Who's most likely to go on a rant about something nobody cares about?",
  "Who here has the most controversial opinions?",
  "Who's most likely to start a political argument at dinner?",
  "Who here is secretly the richest?",
  "Who's most likely to be secretly broke?",
  "Who here spends the most on food delivery?",
  "Who's most likely to tip the worst?",
  "Who here would be the most fun at a sleepover?",
  "Who's most likely to suggest 'let's play paranoia' at 3 AM?",
  "Who here has the most chaotic Snapchat stories?",
  "Who's most likely to post something they regret at 4 AM?",
  "Who here gives off the most husband/wife material vibes?",
  "Who's most likely to be someone's 'the one that got away'?",
  "Who here would be the best at keeping a surprise?",
  "Who's most likely to accidentally spoil everything?",
  "Who here is the most emotionally mature?",
  "Who's most likely to handle rejection the worst?",
  "Who here would be the best therapist?",
  "Who's most likely to need a therapist the most but refuse to go?",
  "Who here has the most magnetic eyes?",
  "Who's most likely to seduce someone with just a look?",
  "Who here has the deepest voice?",
  "Who's most likely to have the sexiest phone voice?",
  "Who here would look best in a uniform?",
  "Who's most likely to have a thing for people in uniforms?",
  "Who here has the best legs?",
  "Who's most likely to skip leg day?",
  "Who here gives off old soul energy?",
  "Who's most likely to act like a grandparent at 25?",
  "Who here would be the best at a roast battle?",
  "Who's most likely to cry if they got roasted?",
  "Who here has the most pent-up frustration?",
  "Who's most likely to snap one day?",
  "Who here is the most patient?",
  "Who's most likely to lose their patience over something small?",
  "Who here would you want to be quarantined with?",
  "Who's most likely to go crazy in isolation?",
  "Who here has the best taste in movies?",
  "Who's most likely to judge you for your movie taste?",
  "Who here is the most likely to have a secret talent?",
  "Who's most likely to be hiding an amazing singing voice?",
  "Who here would be the best at improv?",
  "Who's most likely to freeze when put on the spot?",
  "Who here has the warmest hands?",
  "Who's most likely to always have cold feet?",
  "Who here gives the best compliments?",
  "Who's most likely to give a backhanded compliment?",
  "Who here is the most self-aware?",
  "Who's most likely to be completely oblivious about themselves?",
  "Who here has the most natural beauty?",
  "Who's most likely to look completely different without filters?",
  "Who here would win a 'who wore it best' competition?",
  "Who's most likely to show up to an event in the same outfit as someone else?",
  "Who here has the healthiest relationship with themselves?",
  "Who's most likely to be their own worst enemy?",
];
